Feature/added create and remove book interaction
williamrolando88/bookstore pull request #2
Opened 2022-01-18 20:57 UTC by williamrolando88

In this PR, I:
- Created the redux store and actions
- Link the redux store to react app
- Add functions to handle add and remove books
- Add `useEffect` hook to subscribe to redux store
- Unsubscribe from store once unmounting the components

2022-01-18 21:09 UTC, julie-ify requested changes
Hi @williamrolando88, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a project, that does not have a descriptive README. Please consider adding a descriptive README to your repo.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

2022-01-18 23:12 UTC, D4nielJ approved these changes
## Hello @williamrolando88, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

![](https://i.giphy.com/media/IwAZ6dvvvaTtdI8SD5/giphy.webp)

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear or you can always find me on slack!

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-01-18 23:12 UTC, D4nielJ commented on src/components/Books.jsx
> +      unsubscribe;
[OPTIONAL] It seems like we have some issues with our linter configuration. I would like you to take a look at it. This is an image of my console, as you can see, there are plenty of linter errors.

![image](https://user-images.githubusercontent.com/79114233/150026762-4a6cfe5d-4e1f-4345-bd84-70300c59ce8f.png)

I will leave this as optional as I really don't understand why the linters are not stopping CRA from compiling, but I do think that solving these should be a priority. Some are as serious as this line of code where we're calling the `unsubscribe` function incorrectly as it should be something like this.

```
useEffect(() => {
  const subscription = props.source.subscribe();
  return () => {
    // Clean up the subscription
    subscription.unsubscribe();
  };
});
```

You can read more about [cleaning up effects with react here.](https://reactjs.org/docs/hooks-reference.html#useeffect)

2022-01-18 23:12 UTC, D4nielJ commented on src/components/Books.jsx
> +    return () => {};
[OPTIONAL] There is no need to return a function every time we finish a `useEffect` hook. So you can just remove this line of code.

2022-01-18 23:12 UTC, D4nielJ commented on src/components/Books.jsx
> +    return () => {};
[OPTIONAL] Also, Redux provides a custom hook to retrieve state from the store. You might want to consider using it as it makes our lives easier.

```
import { useSelector } from 'react-redux'

export const PostsList = () => {
  const posts = useSelector(state => state.posts)

  return (
    ...
  )
}
```

2022-01-19 14:19 UTC, williamrolando88 commented on src/components/Books.jsx
> +      unsubscribe;
Hi @D4nielJ 
About the unsubscribe, is not that it was called incorrectly, both are ok, I saw a lot of articles while trying to implement this on my application, and they refer to it in both ways. You can see a detailed article about it [here](https://www.pluralsight.com/guides/unsubscribe-in-a-react-component-using-redux).

About the linters errors, now that I discussed it whit some of my teammates, I think I have an idea, since our linters config check for js files, and I'm using jsx maybe that is why the github actions are not triggered about all this errors.

2022-01-19 14:19 UTC, williamrolando88 commented on src/components/Books.jsx
> +    return () => {};
Thank you, I will implement this suggestion right ahead 👍

2022-01-19 14:40 UTC, merged